"""add owner_id to sessions, scenarios and exercises

Revision ID: c0f41c4f1ff4
Revises: b91650fa2a9e
Create Date: 2026-09-27 02:11:38.505484
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0f41c4f1ff4"
down_revision: str | None = "b91650fa2a9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exercises", sa.Column("owner_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_exercises_owner_id"), "exercises", ["owner_id"], unique=False)
    op.add_column("game_sessions", sa.Column("owner_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_game_sessions_owner_id"), "game_sessions", ["owner_id"], unique=False)
    op.add_column("generated_scenarios", sa.Column("owner_id", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_generated_scenarios_owner_id"), "generated_scenarios", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generated_scenarios_owner_id"), table_name="generated_scenarios")
    op.drop_column("generated_scenarios", "owner_id")
    op.drop_index(op.f("ix_game_sessions_owner_id"), table_name="game_sessions")
    op.drop_column("game_sessions", "owner_id")
    op.drop_index(op.f("ix_exercises_owner_id"), table_name="exercises")
    op.drop_column("exercises", "owner_id")
    # ### end Alembic commands ###
